Simple Backend approach for PoC
t-erxleben/marbellous pull request #10
Opened 2021-04-23 14:47 UTC by t-erxleben

closes #6

2021-04-24 16:28 UTC, JBenda requested changes
Expect the communication with the front end, it's looks good.
But in my opinion the front end should be given some self-management :wink: .

2021-04-24 16:28 UTC, JBenda commented on Notes/Backend/components.md
> +- We will make heavy use of emscripten/html5.h to register callbacks for certain events (e.g. clicks on buttons or canvas).
I don't really like that.
This approach requires that every single functionality is part of the backend, and that the Frontend is only buttons.
It would be nicer to define an interface which the frontend can call, then the front end can have a different trigger for one action, and also we can change the structure of the frontend without changing the backend.

2021-04-24 16:36 UTC, t-erxleben commented on Notes/Backend/components.md
> +- We will make heavy use of emscripten/html5.h to register callbacks for certain events (e.g. clicks on buttons or canvas).
Good point, will work on that tomorrow.

2021-04-25 15:26 UTC, JBenda approved these changes
nice

2021-04-25 17:12 UTC, merged