Refactor parts of demo and add new class strucutre
t-erxleben/marbellous pull request #37
Opened 2021-05-08 16:01 UTC by t-erxleben

closes #28, closes #34

2021-05-08 18:26 UTC, JBenda requested changes
Nice general structure, but a few performance concerns (see comnands)

2021-05-08 18:26 UTC, JBenda commented on backend/include/Point.hpp
> +class Point
use `class __attribute__((packed)) Point` to ensure that there is no memory aligment
else it could have side effects if you pass it to opengl

2021-05-08 18:26 UTC, JBenda commented on backend/include/Polygon.hpp
> +        std::forward_list<Point> vertices;
Why no std vector?

2021-05-08 18:26 UTC, JBenda commented on backend/include/Polygon.hpp
> +        std::tuple<std::vector<uint32_t> const, size_t, void const *> getDrawInfo();
the data should be bufferd from the user of this function, else it will copy the indices each time -> expensive

2021-05-09 15:00 UTC, t-erxleben commented on backend/include/Polygon.hpp
> +        std::forward_list<Point> vertices;
Graham explained to us that we would need to insert vertices when displacing colour drops to ensure smooth boundaries. That would be expensive using a vector. However if I recall it right he did not insert new ones in the example he gave us. If it turns out to be unnecessary we can change this later on.

2021-05-09 15:01 UTC, t-erxleben commented on backend/include/Point.hpp
> +class Point
thx for the hint :)

2021-05-09 15:01 UTC, t-erxleben commented on backend/include/Polygon.hpp
> +        std::tuple<std::vector<uint32_t> const, size_t, void const *> getDrawInfo();
good point, will change that

2021-05-14 08:31 UTC, JBenda approved these changes
Looks like a good general structure :)

2021-05-14 12:40 UTC, merged